FROM debian:bookworm-slim

RUN dpkg --add-architecture arm64 && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        gcc-aarch64-linux-gnu \
        libelf-dev:arm64 \
        zlib1g-dev:arm64 \
        clang \
        llvm \
        bpftool \
        make \
    && rm -rf /var/lib/apt/lists/*
